version: '3'

services:
  recruto:
    container_name: recruto
    restart: on-failure

    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile

    command: ./recruto

    environment:
      - HOST=:8080
    

    ports:
      - 8080:8080

